# Generated by Django 5.1.2 on 2025-11-28 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transaction',
            new_name='wallet_tran_wallet__a053af_idx',
            old_name='wallet_tran_wallet__idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='wallet_tran_transac_019d56_idx',
            old_name='wallet_tran_transac_idx',
        ),
    ]
