# Generated by Django 5.1.2 on 2025-11-28 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='referralrelation',
            new_name='users_refer_referre_a4f3cb_idx',
            old_name='users_refer_referre_idx',
        ),
        migrations.RenameIndex(
            model_name='referralrelation',
            new_name='users_refer_user_id_2a849c_idx',
            old_name='users_refer_user_id_idx',
        ),
    ]
